### ISSUE TITLE
Exception on Nullable type

### ISSUE THREAD

**Issue by codepend** [NickPolyder/NP.ObjectComparison#1]
On version 0.9.7
After making a few properties on a class nullable, I received the following unhandled exception on checking HasChanges()

There are some null values on some of the properties, though they "construct" okay, but when calling HasChanges it throws the error.

Message:
"Expression must be writeable (Parameter 'left')"

Stack Trace:
"   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)\r\n   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)\r\n   at NP.ObjectComparison.Analyzers.Infos.ObjectInfoBuilder`1.Build(PropertyInfo publicProperty)\r\n   at NP.ObjectComparison.Analyzers.Strategies.ObjectAnalyzerBuilderStrategy.Build[TInstance](PropertyInfo propertyInfo, AnalyzerSettings options)\r\n   at NP.ObjectComparison.Analyzers.AnalyzerBuilder`1.<Build>d__0.MoveNext()\r\n   at NP.ObjectComparison.Analyzers.ComplexObjectAnalyzer`2.Analyze(TInstance originalInstance, TInstance targetInstance)\r\n   at NP.ObjectComparison.Analyzers.AnalyzerComposite`1.Analyze(TInstance originalInstance, TInstance targetInstance)\r\n   at NP.ObjectComparison.ComparisonTracker`1.Analyze()\r\n   at NP.ObjectComparison.ComparisonTracker`1.HasChanges(Boolean autoAnalyze)\r\n   at AgreementUpdater.Pages.UpdateByProduct.<>c.<get_isDirty>b__8_0(ComparisonTracker`1 x) in C:\\Users\\userProfile\\source\\repos\\Clients\\AgreementUpdater\\AgreementUpdater\\Pages\\UpdateByProduct.razor:line 109\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at AgreementUpdater.Pages.UpdateByProduct.get_isDirty() in C:\\Users\\userProfile\\source\\repos\\Clients\\AgreementUpdater\\AgreementUpdater\\Pages\\UpdateByProduct.razor:line 109\r\n   at AgreementUpdater.Pages.UpdateByProduct.BuildRenderTree(RenderTreeBuilder __builder) in C:\\Users\\userProfile\\source\\repos\\Clients\\AgreementUpdater\\AgreementUpdater\\Pages\\UpdateByProduct.razor:line 14\r\n   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)\r\n   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)\r\n   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()"

Line in question in my code:
bool isDirty => additions.Any(x => x.HasChanges(true));

**Comment by codepend** [comment]
i downloaded the repo and created a simple class and can reproduce. Seems like if the class contains nullable properties i crashes on calling HasChanges()

**Comment by NickPolyder** [comment]
I was able to fix it. The code was treating the Nullable properties as complex objects. 

See the fix in the commit: 87e1aa36555c65491e80d659e5ae80818d86ca07

It will be in the version 0.9.8
